### ISSUE TITLE
Questions about PDB

### ISSUE THREAD

**Issue by LifePie1994** [pdbme/pdb-api-doc#1]
Hey,

I left you an email on the porndb.me website, but I didn't receive a reply yet. I hope you don't mind me reaching out on here.

Firstly, PDB looks like a massively useful tool. There's nothing else like it. 

- What's the benefits of the premium membership? I'm happy to pay and support the continued dev of this tool!
- Is the RSS limited to a max of 50 files? If so, how can I change this?
- In one post you mentioned a desktop tool that sends NZBs to SabNZB, but the link leads to a 404 page (https://porndb.me/autodownload/)?

If you'd prefer to chat over email (or somewhere else), please let me know.

**Comment by pdbme** [comment]
Hi LifePie1994,

sorry about the delayed response for your questions regarding porndb

Currently all features are available in the free tier. This might change in the feature, when some features will be limited to premium members - but don't worry there will be a transition phase and everyone will be notified in advance. The packages you can buy now are discounted and offer multiple years premium for a much lower price.

The rss feed we provide is normally used with sabnzbd or nzbget. There isn't really a use case for higher limits. How do you want to use the rss feed that makes a higher limit useful?

Thanks for pointing out the dead link. Just corrected it. Take a look at https://github.com/pdbme/pdbMate we are currently developing a tool that is better suited for downloading porn from usenet than we can currently offer with rss feeds. Rss feeds lead to many duplicates being downloaded. Currently pdbmate only supports duplication detetion and renaming. The adding of nzb files is not included yet but coming soon.

Kind Regards
Steve

**Comment by pdbme** [comment]
By the way your email prodiver returned a  550-5.1.1 The email account that you tried to reach does not exist.

**Comment by LifePie1994** [comment]
Hey Steve,

Thanks for getting back to me and answering my questions. What email address do you have for me? My email is lifepie1994[at]gmail.com.

Thanks,
Mikhaeel

**Comment by pdbme** [comment]
Hey Mikhaeel,

in the support form you missed an e in your email address and so we replied to the wrong address. Your email in our database is correct.

Steve
