### ISSUE TITLE
Issue with Premium Plan

### ISSUE THREAD

**Issue by vodogg25** [pdbme/pdb-api-doc#2]
Hello, 

Let me start by saying thank you for all the hard work you have put into pdbme. I am looking forward to seeing all that you do with the future updates. I wanted to go ahead and support your efforts by donating so I joined the early adopter program by paying with bitcoin. Unfortunately it is not registering that I paid and my account still says "free". Is there a way to fix this? I want to be an early supported of your work. Also, I apologize for reaching out via this method. All attempts to reach out using the support forum came back with an error message. Thank you in advance for your help. My email is ******. I can send you any receipt that you need.

**Comment by pdbme** [comment]
We forwarded your request and you will get an answer and probably your account will be upgraded. For your own safety we redacted your email address.
